# -*- coding: utf-8 -*-
"""Registration Login System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OjePSpmeG5s93lJtI_DqPKPtic1eMTM
"""

fl=open("task.txt","x")
fl

def register():
  fl=open("task.txt","r")
  email=input("create email:")
  password=input("create password:")
  password1=input("conform password:")
  d=[]
  f=[]
  for i in fl:
    a,b=i.split(",")
    b=b.strip()
    d.append(a)
    f.append(b)
  data=dict(zip(d, f))
#  print(data)
  if password!=password1:
    print("password is wrong,restart")
    register()
  else:
   if len(password)<5:
      print("password is  short,restart:") 
      register() 
   elif email in d:
      print("email exists")
      register()
   else:
      fl=open("task.txt","a")
      fl.write(email+","+password+"\n")
      print("success")    
#register() 

def display():
  fl=open("task.txt","r")
  email=input("enter email:")
  password=input("enter password:")

  if not len(email or password)<5:
    d=[]
    f=[]
    for i in fl:
      a,b=i.split(",")
      b=b.strip()
      d.append(a)
      f.append(b)
    data=dict(zip(d, f))
    if data[email]:
      try:
        if password==data[email]:
          print("login successfull")
        else:
          print("email or password incorrect")
      except:
        print("email or password doesn't exists")
    else:
      print("email or password doesn't exists")
  else:
    print("enter valid email")
#register()
def home(option=None):
  option=input("Login | Signup:")
  if option=="Login":
    display()
  elif option=="Signup":
    register()
  else:
    print("enter option")

home()